### ISSUE TITLE
Mac version of Shelley stopped working

### ISSUE THREAD

**Issue by ondrejhanslik** [TestingWithFrank/Shelley#12]
There was a commit which replaced the view hierarchy traversing by using a method called `FEX_children`.

The method is nowhere to be found and all Mac unit tests are failing because of the fact.

**Comment by MichaelBuckley** [comment]
That is my fault. The tests were still working on my machine because I was accidentally loading Frank into the Shelley tests. I will add suitable implementations of FEX_children and FEX_parent to the Shelley tests. Sorry about that!

**Comment by ondrejhanslik** [comment]
Not a problem for me. I just noticed that recently when I was making some updates. Are the methods actually checked into Frank? I was looking for them but couldn't find them in Frank either.

**Comment by MichaelBuckley** [comment]
They're in the TestingWithFrank repo, but not the moredip repo. I don't have commit priviliges to the moredip repo, so I've been working out of the TestingWithFrank repo and merging from the moredip repo.
